config/routes.rb
Replay::Application.routes.draw do
  match '/suggestions/rss' => 'suggestions#rss'
  resources :suggestions do
      member do
        get 'preview'
        get 'accept'
        get 'deny'
      end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' } do
		get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
		get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session		
	end

	resources :users, :only =>  [:index, :show] do
		resources :reviews do
			collection do
				get 'your'
			end
		end
	end

	match '/reviews/new/:game_id' => 'reviews#new'

	match '/users/:name/followers' => 'users#followers'
	match '/users/:name/following' => 'users#following'
	match '/users/:name/following_template' => 'users#following_template'
	match '/users/:name/followers_template' => 'users#followers_template'
	match '/users/:name/statistics' => 'users#stats'
	match '/users/:name/lists/:rating' => 'users#lists'
	match '/users/:name/invite/:invite_phrase' => 'users#invite'

	match '/sign_up' => 'sign_up#index'
	match '/sign_up/new' => 'sign_up#new'

  match '/stats/new-users' => 'stats#new_users'
  match '/stats/new-reviews' => 'stats#new_reviews'

  resources :tags

  resources :games
    match '/games/:slug/new-review' => 'games#new_review'
	match '/games/import'
	match '/games_oldest' => 'games#oldest'
	match '/games/:slug/reviews' => 'games#reviews'
	match '/games/:slug/duplicates' => 'games#duplicates'
	match '/games/:slug/merge/:with' => 'games#merge'

	resources :invites
	
	match '/profile' => 'profile#index'
	match '/profile/start' => 'profile#start'
	match '/profile/timeline' => 'profile#timeline'
	match '/profile/follow/:name' => 'profile#follow'
	match '/profile/unfollow/:name' => 'profile#unfollow'

	match '/search' => 'search#index'

  match '/import' => 'import#index'
  match '/import/perform' => 'import#perform'

	match '/site' => 'site#index'
	match '/site/tumblr' => 'site#tumblr'

  get "home/index"

	match '/donate' => 'donate#index'

  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

		# Already authenticated, redirect
		if not current_user.nil? then
			redirect_to '/profile'
		end

    @users = User.order('created_at DESC').limit(5)
		@reviews = Review.order('created_at DESC').limit(5)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= content_for :javascript do %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
      var jsonData = [
        $.ajax({
          url: "/stats/new-users",
          dataType: "json",
          async: false,
        }).responseText,
        $.ajax({
          url: "/stats/new-reviews",
          dataType: "json",
          async: false,
          }).responseText
      ];

      var data = [ 
        new google.visualization.DataTable(jsonData[0]),
        new google.visualization.DataTable(jsonData[1])
      ];

      var options = {
        width: 280,
        height: 280,
        legend: { position: 'none' },
        chartArea:{left:25,top:20,width:"85%",height:"80%"}
      };

      new google.visualization.LineChart(document.getElementById('users_chart')).draw(data[0], options);
      new google.visualization.LineChart(document.getElementById('reviews_chart')).draw(data[1], options);
    }
  </script>
<% end %>

<article>
  <h2>What game would you R3PL4Y?</h2>
  <p>
    R3PL4Y is a service for you as a gamer. A place where you can gather impressions about games you play, and share those impressions with your friends.
  </p>
</article>

<article class="stats">
  <div class="user-stats">
    <h2>Users</h2>
    <table>
      <thead>
        <tr>
          <th>Most recent registred</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.name, user %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div id="users_chart" class="chart"></div>
  </div>
  <div class="review-stats">
    <h2>Reviews</h2>
    <table>
      <thead>
        <tr>
          <th>Most recent reviews</th>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td><a href="<%= user_review_path(review.user, review) %>"><%= review.game.title %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div id="reviews_chart" class="chart"></div>
  </div>
  <div class="clear"></div>
</article>

<%= content_for :aside do %>
<aside class="sign_in">
	<h2>Sign in</h2> 
    <p>Choose your favorite identiy provider in order to sign in.</p>
    <%= render :partial => 'devise/identity_providers', :locals => { :user_id => nil, :redirect_url => nil } %>
</aside>

<aside>
	<article>
		<h2>Hello,</h2>
		<p>
			Do you want to contribute to R3PL4Y? We gladly accept all the love you can give us.
			Please contact at <a href="mailto:hello@mikaellundin.name">hello@mikaellundin.name</a>
		</p>
	</article>
</aside>
<% end %>