config/routes.rb
Replay::Application.routes.draw do
  match '/suggestions/rss' => 'suggestions#rss'
  resources :suggestions do
      member do
        get 'preview'
        get 'accept'
        get 'deny'
      end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' } do
		get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
		get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session		
	end

	resources :users, :only =>  [:index, :show] do
		resources :reviews do
			collection do
				get 'your'
			end
		end
	end

	match '/reviews/new/:game_id' => 'reviews#new'

	match '/users/:name/followers' => 'users#followers'
	match '/users/:name/following' => 'users#following'
	match '/users/:name/following_template' => 'users#following_template'
	match '/users/:name/followers_template' => 'users#followers_template'
	match '/users/:name/statistics' => 'users#stats'
	match '/users/:name/lists/:rating' => 'users#lists'
	match '/users/:name/invite/:invite_phrase' => 'users#invite'

	match '/sign_up' => 'sign_up#index'
	match '/sign_up/new' => 'sign_up#new'

  match '/stats/new-users' => 'stats#new_users'
  match '/stats/new-reviews' => 'stats#new_reviews'

  resources :tags

  resources :games
    match '/games/:slug/new-review' => 'games#new_review'
	match '/games/import'
	match '/games_oldest' => 'games#oldest'
	match '/games/:slug/reviews' => 'games#reviews'
	match '/games/:slug/duplicates' => 'games#duplicates'
	match '/games/:slug/merge/:with' => 'games#merge'

	resources :invites
	
	match '/profile' => 'profile#index'
	match '/profile/start' => 'profile#start'
	match '/profile/timeline' => 'profile#timeline'
	match '/profile/follow/:name' => 'profile#follow'
	match '/profile/unfollow/:name' => 'profile#unfollow'

	match '/search' => 'search#index'

  match '/import' => 'import#index'
  match '/import/perform' => 'import#perform'

	match '/site' => 'site#index'
	match '/site/tumblr' => 'site#tumblr'

  get "home/index"

	match '/donate' => 'donate#index'

  root :to => "home#index"

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :reviews, :order => "published DESC"
	has_many :game_tags
	has_many :tags, :through => :game_tags
	has_many :game_words
	has_many :words, :through => :game_words
	
	has_attached_file :thumbnail,
		:styles => {
			:medium => "160x",
      :small => "60x"
		},
		:storage => :aws,
		:s3_credentials => { 
			:access_key_id => ENV['s3_access_key_id'],
		  :secret_access_key => ENV['s3_secret_access_key'],
			:endpoint => 's3-eu-west-1.amazonaws.com' 
		},
		:s3_permissions => :public_read,
		:s3_protocol => 'http',
		:s3_options => {
		  :content_disposition => 'attachment'
		},
		:s3_bucket => 'replay-files.mikaellundin.name',
    :s3_host_alias => 'replay-files.mikaellundin.name',
    :s3_headers => {'Expires' => 1.year.from_now.httpdate},
		:path => ":attachment/:id/:style.:extension"
	
	has_attached_file :background,
		:styles => {
			:full => "800x600#"
		},
		:storage => :aws,
		:s3_credentials => { 
			:access_key_id => ENV['s3_access_key_id'],
		  :secret_access_key => ENV['s3_secret_access_key'],
			:endpoint => 's3-eu-west-1.amazonaws.com'
		},
		:s3_permissions => :public_read,
		:s3_protocol => 'http',
		:s3_options => {
		  :content_disposition => 'attachment'
		},
		:s3_bucket => 'replay-files.mikaellundin.name',
    :s3_host_alias => 'replay-files.mikaellundin.name',
    :s3_headers => {'Expires' => 1.year.from_now.httpdate},
		:path => ":attachment/:id/:style.:extension"




	attr_accessor :your_review, :other_reviews

	validates_uniqueness_of :slug

	def to_param
		slug
	end

	def discrete_average_rating
		if rate_average < 1.8 then
			return 1
		elsif rate_average < 2.6 then
			return 2
		elsif rate_average < 3.4 then
			return 3
		elsif rate_average < 4.2 then
			return 4
		else
			return 5
		end
	end

	def new_review
		Review.new :game_id => @id
	end

	def self.create_slug(title)
		title.downcase.gsub(/[^\w^\s^\d^-]/, '').gsub(/\s/, '-')
	end

	def platforms
		tags.find_all {|tag| tag.category == 'platform'}
	end

	def genres
		tags.find_all {|tag| tag.category == 'genre'}
	end

	def developers
		tags.find_all {|tag| tag.category == 'studio'}
	end

	def publishers
		tags.find_all {|tag| tag.category == 'publisher'}
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	before_filter :authenticate_user!, :except => ['show', 'reviews', 'rss']
  before_filter :authenticate_admin!, :except => ['show', 'reviews', 'rss', 'new_review']

  # GET /games
  # GET /games.json
  def index
    @games = Game.order('title')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

	def oldest
		@games = Game.order('updated_at ASC').limit(50)

		respond_to do |format|
			format.html { render 'index' }
		end
	end



  # GET /games/bastion
  # GET /games/bastion.json
  def show
    @game = Game.where(:slug => params[:id]).first

    # 404
    return render(:text => 'Not found', :status => 404) if @game.nil?
    # 403
    return render(:text => 'Forbidden', :status => 403) if not @game.is_public and (current_user and current_user.role != 'admin')
    
		
		from = params['from'] ? DateTime.parse(params['from']) : DateTime.now()
		@reviews = reviews_for_game(@game.slug, from)

    respond_to do |format|
      if current_user
        format.html { render :layout => 'profile' }
        format.text { render :layout => false }
        format.rss { render :layout => false }
      else
        format.html # show.html.erb
        format.json { render json: @game }
        format.rss { render :layout => false }
        format.text { render :layout => false }
      end
    end
  end

  def new_review
    
    @game = Game.where(:slug => params[:slug]).first
	@reviews = reviews_for_game(@game.slug, DateTime.now())
    
    respond_to do |format|
        format.html { render :layout => 'profile' }
        format.text { render 'show.text.erb', :layout => false }
    end
  end

	def reviews_for_game(slug, from)
		Review.joins(:game).where("games.slug = :slug AND published <= :from", { :slug => slug, :from => from }).order('published DESC').limit(11)
	end

	def reviews
		slug = params[:slug]
		from = params['from'] ? DateTime.parse(params['from']) : DateTime.now()

		@reviews = reviews_for_game(slug, from) 

		respond_to do |format|
			format.text { render :partial => 'reviews/game_reviews.text.erb', :object => @reviews }
		end
	end

	def duplicates
		@slug = params[:slug]
		words = @slug.split('-')

		sql = "SELECT * FROM games INNER JOIN ("
		sql += "SELECT gw.game_id"

		for i in 1..words.length do
			sql += ", max(w#{i}.id) as word#{i}"
		end

		sql += " FROM game_words gw "

		# join for every word
		for i in 1..words.length do
			sql += "LEFT JOIN words w#{i} ON w#{i}.id = gw.word_id AND w#{i}.word = ? "
		end

		sql += "WHERE "

		# filter those not matching
		for i in 1..words.length do
			sql += "w#{i}.word = ? "
			sql += "OR " unless i == words.length # last
		end

		sql += "GROUP BY gw.game_id ORDER BY "

		# fix ordering
		for i in 1..words.length do
			sql += "word#{i}"
			sql += ", " unless i == words.length # last
		end

		sql += " LIMIT 10) AS words ON id = words.game_id"
		sql += " WHERE slug != ?"
		query = [sql] + (words * 2) + [@slug]
		@duplicates = Game.find_by_sql query
	end

	def rss
		@game = Game.find_by_slug(params[:id])
  	@reviews = Review.find(:all, :order => "id DESC", :limit => 10)
  	render :layout => false
  	response.headers["Content-Type"] = "application/xml; charset=utf-8"
	end

	# GET /games/:id/merge/:with
	def merge
		@original = Game.find_by_slug(params[:slug])
		@copy = Game.find_by_slug(params[:with])

    ActiveRecord::Base.transaction do
      # move reviews
      ActiveRecord::Base.connection.execute "UPDATE reviews SET game_id = #{@original.id} WHERE game_id = #{@copy.id}"

      # move suggestions
      ActiveRecord::Base.connection.execute "UPDATE suggestions SET game_id = #{@original.id} WHERE game_id = #{@copy.id}"

      # remove GameWords
      ActiveRecord::Base.connection.execute "DELETE FROM game_words WHERE game_id = #{@copy.id}" 

      # join tags
      @original.tags = @original.tags | @copy.tags

      # save original
      @original.save

      # destroy the copy
      @copy.destroy
    end

    respond_to do |format|
      format.html { render @original }
      format.json { head :ok }
    end

	end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

		@platforms_list = Tag.where("category = 'platform'").order('name').collect {|t| [t.name, t.id]}
		@platforms_selected = [] 

		@genres_list = Tag.where("category = 'genre'").order('name').collect {|t| [t.name, t.id]}
		@genres_selected = []

		@publishers_list = Tag.where("category = 'publisher'").order('name').collect {|t| [t.name, t.id]}
		@publishers_selected = [] 

		@developers_list = Tag.where("category = 'studio'").order('name').collect {|t| [t.name, t.id]}
		@developers_selected = []

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find_by_slug(params[:id])

		@game_tags = GameTag.where("game_id = ?", @game.id)
		@tags_list = []

		@game_tags.each do |tags|
			@tags_list << tags.tag_id
		end

		@platforms_list = Tag.where("category = 'platform'").order('name').collect {|t| [t.name, t.id]}
		@platforms_selected = GameTag.joins(:tag).where("game_id = :game_id AND tags.category = 'platform'", :game_id => @game.id).collect {|t| t.tag_id}

		@genres_list = Tag.where("category = 'genre'").order('name').collect {|t| [t.name, t.id]}
		@genres_selected = GameTag.joins(:tag).where("game_id = :game_id AND tags.category = 'genre'", :game_id => @game.id).collect {|t| t.tag_id}

		@publishers_list = Tag.where("category = 'publisher'").order('name').collect {|t| [t.name, t.id]}
		@publishers_selected = GameTag.joins(:tag).where("game_id = :game_id AND tags.category = 'publisher'", :game_id => @game.id).collect {|t| t.tag_id}

		@developers_list = Tag.where("category = 'studio'").order('name').collect {|t| [t.name, t.id]}
		@developers_selected = GameTag.joins(:tag).where("game_id = :game_id AND tags.category = 'studio'", :game_id => @game.id).collect {|t| t.tag_id}
  end

	def build_tags_from_params(params)
		tag_ids = []
		tag_ids |= params[:platforms] || []
		tag_ids |= params[:genres] || []
		tag_ids |= params[:publishers] || []
		tag_ids |= params[:developers] || []

		tags = Tag.find(tag_ids)

		# add any new platforms
		new_tags(params[:new_platforms], 'platform').each do |platform|
			tags.push(platform) unless @game.tags.include?(platform)
		end

		# add any new genres
		new_tags(params[:new_genres], 'genre').each do |genre|
			tags.push(genre) unless @game.tags.include?(genre)
		end

		# add any new publishers
		new_tags(params[:new_publishers], 'publisher').each do |publisher|
			tags.push(publisher) unless @game.tags.include?(publisher)
		end

		# add any new developers
		new_tags(params[:new_developers], 'studio').each do |developer|
			tags.push(developer) unless @game.tags.include?(developer)
		end

		return tags
	end

	def new_tags(input, category)
		tags = input.split(';').map{|tag| tag.strip}

		tags.collect do |tag_name|
			Tag.find_by_name_and_category(tag_name, category) || Tag.create(:name => tag_name, :category => category, :description => '')
		end
	end

  # POST /games
  # POST /games.json
  def create
    @game = Game.create(params[:game])
		@game.rate_average = 0.0
		@game.rate_quantity = 0	
		@game.tags = build_tags_from_params(params) if params[:commit] == 'Update Game' 

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find_by_slug(params[:id])
		@game.tags = build_tags_from_params(params) if params[:commit] == 'Update Game'

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find_by_slug(params[:id])
    
    ActiveRecord::Base.transaction do
      @game.reviews.each {|review| review.destroy}

      # remove GameWords
      ActiveRecord::Base.connection.execute "DELETE FROM game_words WHERE game_id = #{@game.id}" 

      @game.destroy
    end

    respond_to do |format|
      format.html { redirect_to profile_url }
      format.json { head :ok }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
	# only output title if not empty
	def tag_link(tag, options)
		if options.has_key?(:title) and options[:title].empty? then
			options.delete(:title)
		end

		link_to(tag.name, tag, options)
	end
end

app/views/games/_form.html.erb
<style>
#game_released_3i,
#game_released_4i,
#game_released_5i {
	display: none; 
}	
</style>
<%= form_for @game do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :released %><br />
    <%= f.datetime_select :released, :start_year => 1980, :prompt => {:month => 'Choose month', :year => 'Choose year'}  %>
  </div>
  <div class="field">
    <%= f.label :rate_average %><br />
    <%= f.text_field :rate_average, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :rate_quantity %><br />
    <%= f.text_field :rate_quantity, :disabled => true %>
  </div>
	
	<div class="field">
		<%# f.label :tags %><br />
		<%# select_tag :tags, options_for_select(Tag.all.collect {|t| [ t.name, t.id ] }, @tags_list), :multiple => true %>
	</div>
	<div class="tags">

		<!-- Platforms -->
		<div class="field">
			<%= f.label :platforms %><br />
			<%= select_tag :platforms, options_for_select(@platforms_list, @platforms_selected), :multiple => true %>
			<%= text_field_tag :new_platforms %>
		</div>

		<!-- Genre -->
		<div class="field">
			<%= f.label :genres %><br />
			<%= select_tag :genres, options_for_select(@genres_list, @genres_selected), :multiple => true %>
			<%= text_field_tag :new_genres %>
		</div>

		<!-- Publishers -->
		<div class="field">
			<%= f.label :publishers %><br />
			<%= select_tag :publishers, options_for_select(@publishers_list, @publishers_selected), :multiple => true %>
			<%= text_field_tag :new_publishers %>
		</div>

		<!-- Developers -->
		<div class="field">
			<%= f.label :developers %><br />
			<%= select_tag :developers, options_for_select(@developers_list, @developers_selected), :multiple => true %>
			<%= text_field_tag :new_developers %>
		</div>
		<div class="clear"></div>
	</div>

	<div class="field">
		<%= f.label :is_public %><br />
		<%= f.check_box :is_public %>
	</div>
  <div class="actions">
    <%= f.submit 'Update Game' %>
  </div>
<% end %>

<h2>Upload thumbnail</h2>
<%= form_for @game, :html => { :multipart => true } do |f| %>
	<div class="field">
		<%= f.label :thumbnail %>
		<%= f.file_field :thumbnail %>
	</div>
  <div class="actions">
    <%= f.submit 'Update Thumbnail' %>
  </div>
<% end %>

<h2>Upload background</h2>
<%= form_for @game, :html => { :multipart => true } do |f| %>
	<div class="field">
		<%= f.label "Background" %>
		<%= f.file_field :background %>
	</div>
  <div class="actions">
    <%= f.submit 'Update Background' %>
  </div>
<% end %>

app/views/games/_list.html.erb
<ul class="game-list">
	<% list.each do |game| %>
	<li class="game">
		<h2>
			<%= link_to (game) do %>
				<%= image_tag game.thumbnail.url, :class => 'thumbnail'  %>
				<span class="name"><%= game.title %></span>	
			<% end %>
		</h2>
		<% if current_user and current_user.has_rated?(game) %>
		<span class="your-rating rating rating-<%= current_user.last_review_of(game).rating %>"><%= current_user.last_review_of(game).rating %></span>

		<% elsif game.rate_quantity > 4 %>
		<span class="rating rating-<%= game.discrete_average_rating %>"><%= game.discrete_average_rating %></span>
		<% end %>
		<%= render :partial => 'games/tags', :object => game %>
		<div class="clear"></div>
	</li>
	<% end %>
</ul>

app/views/games/_list.text.erb
<% list.each do |game| %>
<li>	
	<%= link_to(game, :class => 'game-link') do %>
		<%= image_tag game.thumbnail(:medium), :class => 'game-cover' %>
		<span class="game-title"><%= game.title %></span>
	<% end %>

	<%= render :partial => 'games/tags.html.erb', :object => game %>

	<% if current_user and current_user.has_rated?(game) %>
	<span class="your-rating rating rating-<%= current_user.last_review_of(game).rating %>"><%= current_user.last_review_of(game).rating %></span>

	<% elsif game.rate_quantity > 4 %>
	<span class="rating rating-<%= game.discrete_average_rating %>"><%= game.discrete_average_rating %></span>
	<% end %>
</li>
<% end %>

app/views/games/_tags.html.erb
<div class="tags">

	<% if !tags.platforms.empty? %>
	<em>Platform:</em>
	<% tags.platforms.each do |tag| %>
		<%#= tag_link(tag, :title => tag.description) %>
		<span class="tag-link" title="<%= tag.description %>"><%= tag.name %></span>
	<% end %>
	<% end %>


	<% if !tags.genres.empty? %>
	<em>Genre:</em>
	<% tags.genres.each do |tag| %>
		<%# tag_link(tag, :title => tag.description) %>
		<span class="tag-link" title="<%= tag.description %>"><%= tag.name %></span>
	<% end %>
	<% end %>


	<% if !tags.developers.empty? %>
	<em>Developers:</em>
	<% tags.developers.each do |tag| %>
		<%# tag_link(tag, :title => tag.description)	%>
		<span class="tag-link" title="<%= tag.description %>"><%= tag.name %></span>
	<% end %>
	<% end %>

	<% if !tags.publishers.empty? %>
	<em>Publishers:</em>
	<% tags.publishers.each do |tag| %>
	<%# tag_link(tag, :title => tag.description)	%>
		<span class="tag-link" title="<%= tag.description %>"><%= tag.name %></span>
	<% end %>
	<% end %>

	<% if tags.released %>
	<em>Released:</em> <time class="released" datetime="<%= tags.released.xmlschema %>"><%= tags.released.strftime('%-m') == '1' ? tags.released.strftime('%Y') : tags.released.strftime('%B %Y') %></time>
	<% end %>
</div>

app/views/games/duplicates.text.erb
<% @duplicates.each do |game| %>
<li>
  <%= link_to game_path(game) do %>
    <%= image_tag game.thumbnail.url(:small), :class => 'game-cover' %>
    <span class="game-title"><%= game.title %></span>
  <% end %>

	<%= link_to 'Merge', {:action => 'merge', :slug => @slug, :with => game.slug }, :class => 'merge-button', :confirm => 'Are you sure you want to merge?'  %>
	<% if not game.is_public then %>
		<span class="is-public">Not Public</span>
	<% end %>
</li>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table style="background-color: white">
  <tr>
    <!--<th>Id</th>-->
    <th>Title</th>
    <th>Slug</th>
    <th>Description</th>
    <th>Released</th>
		<th>Public</th>
    <!--<th>Rate average</th>-->
    <!--<th>Rate quantity</th>-->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <!--<td><%= game.id %></td>-->
    <td><%= game.title %></td>
    <td><%= game.slug %></td>
    <td><%= game.description[0..50] %>..</td>
    <td><%= game.released.month %>/<%= game.released.year %> </td>
		<td><%= game.is_public ? '✓' : '' %></td>
    <!--<td><%= game.rate_average %></td>-->
    <!--<td><%= game.rate_quantity %></td>-->
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h2>New game</h2>
<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<article style="background-image: url(<%= @game.background.url(:full) %>)" class="game">

<%= link_to(@game, :class => "game-link") do %>
	<img class="game-cover" src="<%= @game.thumbnail.url(:medium) %>" />
	<span class="game-title"><%= @game.title %></span>
<% end %>

	<%= render :partial => 'games/tags.html.erb', :object => @game %>

	<%= markdown(@game.description) %>

	<div class="gradient"></div>
</article>

<ul id="game-reviews" class="game-list" data-source="<%= url_for(:controller => "games", :action => 'reviews', :slug => @game.slug) %>">
	<%= render :partial => 'reviews/game_reviews.text.erb', :object => @reviews %>
</ul>


<% content_for :aside do %>
<aside class="sign_in">
    <%= render :partial => 'sign_up/review_game', :object => @game %>
</aside>
<% end %>

<%# Set the page title %>
<% content_for :title do %><%= @game.title %><% end %>

<% content_for :rss do %>
<!-- START: rss -->
<link rel="alternate" type="application/rss+xml" title="<%= @game.title %> reviews RSS" href="<%= game_url(@game) %>.rss" />
<!-- END: rss -->
<% end %>

<% content_for :meta do %>
<!-- START: Facebook Open Graph -->
<meta property="fb:app_id"      content="<%= ENV['facebook_app_id'] %>" /> 
<meta property="og:type"        content="game" /> 
<meta property="og:url"         content="<%= game_url(@game) %>" /> 
<meta property="og:title"       content="<%= @game.title %>" /> 
<meta property="og:description" content="<%= @game.description %>" /> 
<meta property="og:image"       content="<%= @game.thumbnail.url %>" /> 
<!-- END: Facebook Open Graph -->

<!-- START: Twitter Summary Card -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@rubriks" />
<meta name="twitter:title" content="<%= "#{@game.title}" %>" />
<meta name="twitter:description" content="<%= truncate(@game.description) %>" />
<meta name="twitter:image" content="<%= @game.thumbnail.url %>" />
<!-- END: Twitter Summary Card -->
<% end %>

<% content_for :head_attr do %>prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# game: http://ogp.me/ns/game#"<% end %>

app/views/games/show.text.erb
<header class="game-actions">
	<div class="game-info">
  <%= link_to('Review this game', { :controller => 'reviews', :action => 'new', :game_id => @game.id }, { :class => 'review-button button', 'data-icon' => '✎' }) %>

	<% if @game.rate_quantity > 4 then %>
		<span class="rating rating-<%= @game.discrete_average_rating %>" title="Based on <%= @game.rate_quantity %> reviews"><%= @game.discrete_average_rating %></span>
	<% end %>
	</div>
</header>

<article style="background-image: url(<%= @game.background.url(:full) %>)" class="game">

	<img class="game-cover" src="<%= @game.thumbnail.url(:medium) %>" />
	<span class="game-title"><%= @game.title %></span>

	<%= render :partial => 'games/tags.html.erb', :object => @game %>

	<%= markdown(@game.description) %>

	<div class="gradient"></div>
</article>

<%# ADMIN PANEL %>
<% if current_user.role == 'admin' then %>
<div class="admin">
	<%= link_to('Edit', { :action => 'edit', :id => @game.slug }, { :class => 'edit-action' }) %>
	<%= link_to 'Destroy', game_path(@game), :confirm => 'Are you sure?', :method => 'delete', :class => 'delete-action' %>
	
	<h3>Possible duplicates</h3>
	<ul class="duplicates-list" data-source="<%= url_for(:action => 'duplicates', :slug => @game.slug) %>">
	</ul>
</div>
<% end %>

<ul class="review-list" data-source="<%= url_for(:controller => 'games', :action => 'reviews', :slug => @game.slug) %>">
	<!-- Dynamic loading is done from client side -->
</ul>