config/routes.rb
Replay::Application.routes.draw do
  match '/suggestions/rss' => 'suggestions#rss'
  resources :suggestions do
      member do
        get 'preview'
        get 'accept'
        get 'deny'
      end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' } do
		get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
		get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session		
	end

	resources :users, :only =>  [:index, :show] do
		resources :reviews do
			collection do
				get 'your'
			end
		end
	end

	match '/reviews/new/:game_id' => 'reviews#new'

	match '/users/:name/followers' => 'users#followers'
	match '/users/:name/following' => 'users#following'
	match '/users/:name/following_template' => 'users#following_template'
	match '/users/:name/followers_template' => 'users#followers_template'
	match '/users/:name/statistics' => 'users#stats'
	match '/users/:name/lists/:rating' => 'users#lists'
	match '/users/:name/invite/:invite_phrase' => 'users#invite'

	match '/sign_up' => 'sign_up#index'
	match '/sign_up/new' => 'sign_up#new'

  match '/stats/new-users' => 'stats#new_users'
  match '/stats/new-reviews' => 'stats#new_reviews'

  resources :tags

  resources :games
    match '/games/:slug/new-review' => 'games#new_review'
	match '/games/import'
	match '/games_oldest' => 'games#oldest'
	match '/games/:slug/reviews' => 'games#reviews'
	match '/games/:slug/duplicates' => 'games#duplicates'
	match '/games/:slug/merge/:with' => 'games#merge'

	resources :invites
	
	match '/profile' => 'profile#index'
	match '/profile/start' => 'profile#start'
	match '/profile/timeline' => 'profile#timeline'
	match '/profile/follow/:name' => 'profile#follow'
	match '/profile/unfollow/:name' => 'profile#unfollow'

	match '/search' => 'search#index'

  match '/import' => 'import#index'
  match '/import/perform' => 'import#perform'

	match '/site' => 'site#index'
	match '/site/tumblr' => 'site#tumblr'

  get "home/index"

	match '/donate' => 'donate#index'

  root :to => "home#index"

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_filter :authenticate_user!, :except => ["rss"]
  before_filter :authenticate_admin!, :except => ["show", "create", "rss"]

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = Suggestion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @suggestions }
    end
  end

  def rss
    @suggestions = Suggestion.order("created_at DESC").limit(10)

    respond_to do |format|
      format.rss { render layout: false }
    end
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
    @suggestion = Suggestion.new
    @suggestion.game = Game.find_by_slug(params[:id])
    @suggestion.user = current_user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @suggestion }
    end
  end

  def preview
    suggestion = Suggestion.find(params[:id])
    @game = Game.find(suggestion.game_id)
    @game.description = suggestion.description
    @reviews = []
    render 'games/show'
  end

  def accept
    suggestion = Suggestion.find(params[:id])
    game = Game.find(suggestion.game_id)
    
    suggestion.accepted = true
    game.description = suggestion.description

    suggestion.save
    game.save

    redirect_to :action => "index", :notice => "Accepted description for #{game.title} from #{suggestion.user.name}"
  end

  def deny
    suggestion = Suggestion.find(params[:id])
    game = Game.find(suggestion.game_id)
    
    suggestion.accepted = false
    game.description = "[Suggest a description for this game.](/suggestion/#{game.slug})"

    suggestion.save
    game.save

    redirect_to :action => "index", :notice => "Denied description for #{game.title} from #{suggestion.user.name}"
  end

  # GET /suggestions/1/edit
  def edit
    @suggestion = Suggestion.find(params[:id])
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(params[:suggestion])
    @suggestion.user = current_user

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to :controller => 'profile', :action => 'index', notice: 'Suggestion was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /suggestions/1
  # PUT /suggestions/1.json
  def update
    @suggestion = Suggestion.find(params[:id])

    respond_to do |format|
      if @suggestion.update_attributes(params[:suggestion])
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br />
    <%= f.check_box :accepted %>
  </div>
  <div class="field">
    <%= f.label :game %><br />
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Editing suggestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<section class="suggestion">
<h2>Listing suggestions</h2>

<table>
  <tr>
    <th>Description</th>
    <th>Game</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @suggestions.each do |suggestion| %>
  <tr>
    <td><%= truncate(suggestion.description, :length => 15) %></td>
    <td><%= suggestion.game.title %></td>
    <td><%= suggestion.user.name %></td>
    <td><%= link_to 'Preview', preview_suggestion_path(suggestion) %></td>
    <td><%= link_to 'Edit', edit_suggestion_path(suggestion) %></td>
    <% if suggestion.accepted %>
      <td><%= link_to 'Deny', deny_suggestion_path(suggestion) %></td>
    <% else %>
      <td><%= link_to 'Accept', accept_suggestion_path(suggestion) %></td>
    <% end %>
  </tr>
<% end %>
</table>
</section>

app/views/suggestions/show.html.erb
<section class="suggestion">
    <h2>Suggest description for <%= @suggestion.game.title %></h2>
    <%= image_tag @suggestion.game.thumbnail.url(:small), :class => 'game-cover' %>
    <p>
        Please suggest a short story about the game narrative, without spoiling the story.
    </p>
    <p>
        Do not include information about game play, controls, platforms, genre, developers, publishers, prequels, sequels, graphics, sound, style, age, or anything that is not connected to the game's story. Let reviews take these conclusions.
    </p>
    <%= form_for @suggestion do |s| %>
        <%= s.hidden_field :game_id %>
        <%= s.label :description %>
        <%= s.text_area :description %>
        <%= s.submit "Send" %>
    <% end %>
</section>